apiVersion: v1
kind: ReplicationController
metadata:
  name: mix1
spec:
  replicas: 250
  selector:
    app: mix1
  template:
    metadata:
      labels:
        app: mix1
    spec:
      nodeSelector:
        node: node3
      containers:
      - name: ubuntuv14
        command: ["/run.sh"]
        image: qianyuqiao/ubuntu:v1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          protocol: TCP

      - name: httpd
        image: httpd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP

      dnsConfig:
        nameservers:
        - 114.114.114.114
      restartPolicy: Always
